name: clean_config
version: 0.1.4
author: Clean Team <clean@vacuumlabs.com>
description: Simple library for managing configuration.
homepage: https://github.com/cleandart/clean_config
documentation: https://github.com/cleandart/clean_config
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
